; last modified 1 April 2001 by John Doe
[RUN]
F1 = CQ DE {MYCALL}
F2 = {RST} {EXCH}
F3 = {EXCH}
F4 = {MYCALL}
F5 =  AGN
F6 =  NR
F7 = {RST}
F8 = QRZ
F9 = {HISCALL}
F10 = ?

[S&P]
F1 = CQ DE {MYCALL}
F2 = {RST} {EXCH}
F3 = {EXCH}
F4 = {MYCALL}
F5 =  AGN
F6 =  NR
F7 = {RST}
F8 = QRZ
F9 = {HISCALL}
F10 = ?