#include "export.h"
#include "db.h"
#include "qso.h"

static const char *cabrillo_mode_from_qso_mode(const char *mode) {
  if (!mode || !mode[0])
    return "PH";

  if (strcmp(mode, "CW") == 0)
    return "CW";

  if (strcmp(mode, "SSB") == 0)
    return "PH";

  if (strcmp(mode, "RTTY") == 0)
    return "RY";

  return "DG";
}

/*
 * Export the current logbook to CSV, using the database layer when available.
 *
 * @param filename Output file path.
 * @return 0 on success, or -1 on failure.
 */
int export_csv(const char *filename) {
  if (db_export_csv(filename) == 0)
    return 0;

  FILE *f = fopen(filename, "w");
  if (!f)
    return -1;

  fprintf(f, "DATE,UTC,CALL,FREQ,BAND,MODE,RST,COMMENTS,COUNTRY\n");

  for (int i = 0; i < qso_count; i++) {
    QSO *q = &logbook[i];

    if (q->invalid)
      continue;

        fprintf(f, "%s,%s,%s,%d,%s,%s,%s,%s,%s\n", q->date, q->utc, q->call,
          q->freq, q->band, q->mode, q->rst, q->comments, q->country);
  }

  fclose(f);
  return 0;
}

/*
 * Export the current logbook to ADIF, using the database layer when available.
 *
 * @param filename Output file path.
 * @return 0 on success, or -1 on failure.
 */
int export_adif(const char *filename) {
  if (db_export_adif(filename) == 0)
    return 0;

  FILE *f = fopen(filename, "w");
  if (!f)
    return -1;

  fprintf(f, "Generated by Logger\n");
  fprintf(f, "<EOH>\n");

  for (int i = 0; i < qso_count; i++) {
    QSO *q = &logbook[i];

    if (q->invalid)
      continue;

    fprintf(f, "<CALL:%zu>%s", strlen(q->call), q->call);
    fprintf(f, "<QSO_DATE:8>%s", q->date);
    fprintf(f, "<TIME_ON:4>%s", q->utc);
    fprintf(f, "<FREQ:9>%.6f", q->freq / 1000.0);
    fprintf(f, "<BAND:%zu>%s", strlen(q->band), q->band);
    fprintf(f, "<MODE:%zu>%s", strlen(q->mode), q->mode);
    fprintf(f, "<RST_SENT:%zu>%s", strlen(q->rst), q->rst);
    fprintf(f, "<RST_RCVD:%zu>%s", strlen(q->rst), q->rst);
    if (strlen(q->comments)) {
      fprintf(f, "<COMMENT:%zu>%s", strlen(q->comments), q->comments);
    }

    if (strlen(q->exchange_sent)) {
      fprintf(f, "<STX_STRING:%zu>%s", strlen(q->exchange_sent),
              q->exchange_sent);
    }

    if (strlen(q->exchange_recv)) {
      fprintf(f, "<SRX_STRING:%zu>%s", strlen(q->exchange_recv),
              q->exchange_recv);
    }

    if (strlen(q->contest_id)) {
      fprintf(f, "<CONTEST_ID:%zu>%s", strlen(q->contest_id), q->contest_id);
    }

    if (q->radio_nr > 0) {
      char radio_text[8];
      snprintf(radio_text, sizeof(radio_text), "%d", q->radio_nr);
      fprintf(f, "<APP_CONTESTLOGGER_RADIO:%zu>%s", strlen(radio_text),
              radio_text);
    }

    if (strlen(q->country)) {
      fprintf(f, "<COUNTRY:%zu>%s", strlen(q->country), q->country);
    }

    fprintf(f, "<EOR>\n");
  }

  fclose(f);
  return 0;
}

int export_cabrillo(const char *filename, const ContestDefinition *definition,
                    const char *station_call) {
  if (!filename || !filename[0] || !definition || !station_call ||
      !station_call[0])
    return -1;

  FILE *f = fopen(filename, "w");
  if (!f)
    return -1;

  fprintf(f, "START-OF-LOG: 3.0\n");
  fprintf(f, "CONTEST: %s\n",
          definition->cabrillo_name[0] ? definition->cabrillo_name : "GENERAL");
  fprintf(f, "CALLSIGN: %s\n", station_call);
  fprintf(f, "CATEGORY-OPERATOR: %s\n",
          definition->category_operator[0] ? definition->category_operator
                                           : "SINGLE-OP");
  fprintf(f, "CATEGORY-BAND: %s\n",
          definition->category_band[0] ? definition->category_band : "ALL");
  fprintf(f, "CATEGORY-POWER: %s\n",
          definition->category_power[0] ? definition->category_power : "LOW");
  fprintf(f, "CATEGORY-MODE: %s\n",
          definition->mode[0] ? definition->mode : "MIXED");
  if (definition->category_overlay[0])
    fprintf(f, "CATEGORY-OVERLAY: %s\n", definition->category_overlay);
  if (definition->station_location[0])
    fprintf(f, "LOCATION: %s\n", definition->station_location);
  if (definition->operators[0])
    fprintf(f, "OPERATORS: %s\n", definition->operators);

  for (int i = 0; i < qso_count; i++) {
    QSO *q = &logbook[i];

    if (q->invalid)
      continue;

    const char *sent = q->exchange_sent[0] ? q->exchange_sent
                                           : definition->exchange_sent_template;
    const char *recv = q->exchange_recv[0] ? q->exchange_recv : "000";

    fprintf(f,
            "QSO: %5d %-2s %4.4s-%2.2s-%2.2s %4.4s %-13s %-3s %-6s %-13s %-3s %-6s\n",
            q->freq, cabrillo_mode_from_qso_mode(q->mode), q->date,
            q->date + 4, q->date + 6, q->utc, station_call, q->rst, sent,
            q->call, q->rst, recv);
  }

  fprintf(f, "END-OF-LOG:\n");

  fclose(f);
  return 0;
}
