LAT=52,000000
LON=21,000000
LOCATOR=JO92DF

DXC_HOST=telnet.reversebeacon.net
DXC_PORT=7000
DXC_CALL=SP6AA

CAT_MODEL=1042
CAT_DEVICE=/dev/ttyUSB0
CAT_BAUD=38400
CAT_DATA_BITS=8
CAT_STOP_BITS=1
CAT_PARITY=None
CAT_HANDSHAKE=None
CAT_MODE_FROM_RIG=1
CAT2_MODEL=2
CAT2_DEVICE=/dev/ttyUSB1
CAT2_BAUD=9600
CAT2_DATA_BITS=8
CAT2_STOP_BITS=1
CAT2_PARITY=None
CAT2_HANDSHAKE=None

STATION_CALL=N0CALL
OPERATOR_NAME=
CONTEST_DEF_FILE=contest_defs/iaru_hf_championship.conf
CONTEST_TX_EXCHANGE=29
CONTEST_TECHNIQUE=SO1R

CW_DEVICE=/dev/ttyUSB1
CW_KEYER_LINE=DTR
CW_WPM=20
