NAME=CQ-WPX-CW
CABRILLO_NAME=CQ-WPX-CW
MODE=CW
CATEGORY_OPERATOR=SINGLE-OP
CATEGORY_BAND=ALL
CATEGORY_POWER=LOW
VALIDATE_OPERATING_RULES=1
ALLOWED_MODES=CW
ALLOWED_BANDS=160M,80M,40M,20M,15M,10M
CATEGORY_OVERLAY=
STATION_LOCATION=DX
OPERATORS=
EXCHANGE_SENT=#
SERIAL_WIDTH=3
MULTIPLIER=PREFIX
BONUS_POINTS=0
FIELD=SERIAL,Rcv Nr,required
SCORING_RULE=1;SAME_COUNTRY=1
SCORING_RULE=4;SOURCE_CONTINENT=NA;DESTINATION_CONTINENT=NA;BAND_CLASS=LOW
SCORING_RULE=2;SOURCE_CONTINENT=NA;DESTINATION_CONTINENT=NA
SCORING_RULE=2;SAME_CONTINENT=1;BAND_CLASS=LOW
SCORING_RULE=1;SAME_CONTINENT=1
SCORING_RULE=6;BAND_CLASS=LOW
SCORING_RULE=3
