NAME=CQ-WPX-CW
CABRILLO_NAME=CQ-WPX-CW
MODE=CW
CATEGORY_OPERATOR=SINGLE-OP
CATEGORY_BAND=ALL
CATEGORY_POWER=LOW
CATEGORY_OVERLAY=
STATION_LOCATION=DX
OPERATORS=
EXCHANGE_SENT=#
POINTS_PER_QSO=1
POINTS_CW=0
POINTS_PHONE=0
POINTS_DIGI=0
POINTS_NEW_DXCC=0
POINTS_SAME_DXCC=0
POINTS_NEW_BAND_DXCC=0
POINTS_SAME_BAND_DXCC=0
MULTIPLIER=DXCC
BONUS_POINTS=0
