# EU HF Championship - SSB
# Source: https://dxlog.net/sw/files/download/contest/EUHFC.txt
#
# Extended adaptation note:
# - Official multiplier is license year (CUSTOM per band), unsupported as
#   native multiplier family in current logger scoring.
# - We intentionally set MULTIPLIER=NONE to avoid incorrect multiplier totals.
# - Exchange remains free-text year.

NAME=EU-HF-CHAMPIONSHIP-SSB
CABRILLO_NAME=EUHFC
MODE=SSB
CATEGORY_OPERATOR=SINGLE-OP
CATEGORY_BAND=ALL
CATEGORY_POWER=LOW
CATEGORY_OVERLAY=
STATION_LOCATION=DX
OPERATORS=
EXCHANGE_SENT=#
POINTS_PER_QSO=1
MULTIPLIER=NONE
BONUS_POINTS=0
DOUBLE_QSO=1
FIELD=YEAR,Rcv Year,required
