# EU HF Championship
# Source: https://dxlog.net/sw/files/download/contest/EUHFC.txt
#
# Extended adaptation note:
# - Official multiplier is license year (CUSTOM, PER_BAND), unsupported as native
#   multiplier family in current logger scoring.
# - We set MULTIPLIER=NONE to avoid misleading multiplier math.
# - Exchange remains license-year-like free text in one field.
# - Per-band-mode duplicate nuances are simplified to general duplicate handling.

NAME=EU-HF-CHAMPIONSHIP
CABRILLO_NAME=EUHFC
MODE=MIXED
CATEGORY_OPERATOR=SINGLE-OP
CATEGORY_BAND=ALL
CATEGORY_POWER=LOW
CATEGORY_OVERLAY=
STATION_LOCATION=DX
OPERATORS=
EXCHANGE_SENT=#
POINTS_PER_QSO=1
MULTIPLIER=NONE
BONUS_POINTS=0
DOUBLE_QSO=1
FIELD=YEAR,Rcv Year,required
