#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Użycie:
  ./generate_logger_conf.sh [plik_wyjściowy]

Domyślna nazwa pliku wyjściowego: logger.conf
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

OUTPUT="${1:-logger.conf}"

ask() {
  local prompt="$1"
  local default_value="${2:-}"
  local value=""

  if [[ -n "$default_value" ]]; then
    read -r -p "$prompt [$default_value]: " value
  else
    read -r -p "$prompt: " value
  fi

  if [[ -z "$value" ]]; then
    value="$default_value"
  fi

  printf '%s' "$value"
}

ask_bool() {
  local prompt="$1"
  local default_value="$2"
  local value=""

  while true; do
    if [[ -n "$default_value" ]]; then
      read -r -p "$prompt [$default_value]: " value
    else
      read -r -p "$prompt: " value
    fi

    if [[ -z "$value" ]]; then
      value="$default_value"
    fi

    case "${value,,}" in
      y|yes|1|true) printf '1'; return 0 ;;
      n|no|0|false) printf '0'; return 0 ;;
      *) echo "Wpisz tak/nie, y/n, 1/0." >&2 ;;
    esac
  done
}

station_call="$(ask "Znak stacji" "N0CALL")"
operator_name="$(ask "Nazwa operatora" "")"
locator="$(ask "Lokator Maidenhead" "")"
lat="$(ask "Szerokość geograficzna (LAT)" "0.000000")"
lon="$(ask "Długość geograficzna (LON)" "0.000000")"

dxc_host="$(ask "Host DXCluster" "telnet.reversebeacon.net")"
dxc_port="$(ask "Port DXCluster" "7000")"
dxc_call="$(ask "Call DXCluster" "N0CALL")"

cat_model="$(ask "CAT_MODEL" "2")"
cat_device="$(ask "CAT_DEVICE" "/dev/ttyUSB0")"
cat_baud="$(ask "CAT_BAUD" "9600")"
cat_data_bits="$(ask "CAT_DATA_BITS" "8")"
cat_stop_bits="$(ask "CAT_STOP_BITS" "1")"
cat_parity="$(ask "CAT_PARITY" "None")"
cat_handshake="$(ask "CAT_HANDSHAKE" "None")"
cat_mode_from_rig="$(ask_bool "CAT_MODE_FROM_RIG?" "0")"
cat_auto_connect="$(ask_bool "CAT_AUTO_CONNECT?" "1")"

cat2_model="$(ask "CAT2_MODEL" "2")"
cat2_device="$(ask "CAT2_DEVICE" "/dev/ttyUSB1")"
cat2_baud="$(ask "CAT2_BAUD" "9600")"
cat2_data_bits="$(ask "CAT2_DATA_BITS" "8")"
cat2_stop_bits="$(ask "CAT2_STOP_BITS" "1")"
cat2_parity="$(ask "CAT2_PARITY" "None")"
cat2_handshake="$(ask "CAT2_HANDSHAKE" "None")"

contest_def_file="$(ask "CONTEST_DEF_FILE" "contest.conf")"
contest_tx_exchange="$(ask "CONTEST_TX_EXCHANGE" "")"
contest_technique="$(ask "CONTEST_TECHNIQUE (SO1R/SO2V/SO2R)" "SO1R")"

cw_device="$(ask "CW_DEVICE" "/dev/ttyUSB2")"
cw_keyer_line="$(ask "CW_KEYER_LINE (DTR/RTS)" "DTR")"
cw_wpm="$(ask "CW_WPM" "20")"
cw_auto_connect="$(ask_bool "CW_AUTO_CONNECT?" "1")"

cat > "$OUTPUT" <<EOF
# Generated by generate_logger_conf.sh
LAT=${lat}
LON=${lon}
LOCATOR=${locator}

DXC_HOST=${dxc_host}
DXC_PORT=${dxc_port}
DXC_CALL=${dxc_call}

CAT_MODEL=${cat_model}
CAT_DEVICE=${cat_device}
CAT_BAUD=${cat_baud}
CAT_DATA_BITS=${cat_data_bits}
CAT_STOP_BITS=${cat_stop_bits}
CAT_PARITY=${cat_parity}
CAT_HANDSHAKE=${cat_handshake}
CAT_MODE_FROM_RIG=${cat_mode_from_rig}
CAT_AUTO_CONNECT=${cat_auto_connect}
CAT2_MODEL=${cat2_model}
CAT2_DEVICE=${cat2_device}
CAT2_BAUD=${cat2_baud}
CAT2_DATA_BITS=${cat2_data_bits}
CAT2_STOP_BITS=${cat2_stop_bits}
CAT2_PARITY=${cat2_parity}
CAT2_HANDSHAKE=${cat2_handshake}

STATION_CALL=${station_call}
OPERATOR_NAME=${operator_name}
CONTEST_DEF_FILE=${contest_def_file}
CONTEST_TX_EXCHANGE=${contest_tx_exchange}
CONTEST_TECHNIQUE=${contest_technique}

CW_DEVICE=${cw_device}
CW_KEYER_LINE=${cw_keyer_line}
CW_WPM=${cw_wpm}
CW_AUTO_CONNECT=${cw_auto_connect}
EOF

echo "Utworzono plik konfiguracyjny: $OUTPUT"
